export const CREATE_MARKER: "CREATE_MARKER" = "CREATE_MARKER";
export const DELETE_MARKER: "DELETE_MARKER" = "DELETE_MARKER";
export const MOVE_CENTER: "MOVE_CENTER" = "MOVE_CENTER";
export const DRAG_AND_DROP: "DRAG_AND_DROP" = "DRAG_AND_DROP";
export const CHANGE_POSITION: "CHANGE_POSITION" = "CHANGE_POSITION";
export const CLEAR_ALL_MARKERS: "CLEAR_ALL_MARKERS" = "CLEAR_ALL_MARKERS";
